-- AIR_AIRLINES
ALTER TABLE AIR_AIRLINES ADD CONSTRAINT PK_AIRLINE_ID PRIMARY KEY (AIRLINE_ID);

-- AIR_AIRPLANE_TYPES
ALTER TABLE AIR_AIRPLANE_TYPES ADD CONSTRAINT PK_AIRPLANE_TYPE_ID PRIMARY KEY (AIRPLANE_TYPE_ID);

-- AIR_AIRPLANES
ALTER TABLE AIR_AIRPLANES ADD CONSTRAINT PK_AIRPLANE_ID PRIMARY KEY (AIRPLANE_ID);
ALTER TABLE AIR_AIRPLANES ADD CONSTRAINT FK_AIRLINE_AIRPLANE FOREIGN KEY (AIRLINE_ID) REFERENCES AIR_AIRLINES(AIRLINE_ID);
CREATE INDEX IDX_AL_AP_FX ON AIR_AIRPLANES(AIRLINE_ID);
ALTER TABLE AIR_AIRPLANES ADD CONSTRAINT FK_AIRPLANE_TYPE FOREIGN KEY (AIRPLANE_TYPE_ID) REFERENCES AIR_AIRPLANE_TYPES(AIRPLANE_TYPE_ID);
CREATE INDEX IDX_AP_TYPE_FK ON AIR_AIRPLANES(AIRPLANE_TYPE_ID);

-- AIR_AIRPORTS
ALTER TABLE AIR_AIRPORTS ADD CONSTRAINT PK_AIRPORT_ID PRIMARY KEY (AIRPORT_ID);

-- AIR_AIRPORTS_GEO
ALTER TABLE AIR_AIRPORTS_GEO ADD CONSTRAINT FK_AIRPORTS_GEO FOREIGN KEY (AIRPORT_ID) REFERENCES AIR_AIRPORTS (AIRPORT_ID);
CREATE INDEX IDX_AIRGEO_FK ON AIR_AIRPORTS_GEO(AIRPORT_ID);

-- AIR_PASSENGERS
ALTER TABLE AIR_PASSENGERS ADD CONSTRAINT PK_PASSENGER_ID PRIMARY KEY (PASSENGER_ID);

-- AIR_FLIGHTS_SCHEDULES
ALTER TABLE AIR_FLIGHTS_SCHEDULES ADD CONSTRAINT PK_FLIGHTNO PRIMARY KEY (FLIGHTNO);
ALTER TABLE AIR_FLIGHTS_SCHEDULES ADD CONSTRAINT FK_AL_FLSH FOREIGN KEY (AIRLINE_ID) REFERENCES AIR_AIRLINES(AIRLINE_ID);
CREATE INDEX IDX_AL_FLSH_FK ON AIR_FLIGHTS_SCHEDULES(AIRLINE_ID);
ALTER TABLE AIR_FLIGHTS_SCHEDULES ADD CONSTRAINT FK_FROM_AP_FLSH FOREIGN KEY (FROM_AIRPORT_ID) REFERENCES AIR_AIRPORTS(AIRPORT_ID);
CREATE INDEX IDX_FROM_AP_FLSH_FK ON AIR_FLIGHTS_SCHEDULES(FROM_AIRPORT_ID);
ALTER TABLE AIR_FLIGHTS_SCHEDULES ADD CONSTRAINT FK_TO_AP_FLSH FOREIGN KEY (TO_AIRPORT_ID) REFERENCES AIR_AIRPORTS(AIRPORT_ID);
CREATE INDEX IDX_TO_AP_FLSH_FK ON AIR_FLIGHTS_SCHEDULES(TO_AIRPORT_ID);

-- AIR_FLIGHTS
ALTER TABLE AIR_FLIGHTS ADD CONSTRAINT PK_FLIGHT_ID PRIMARY KEY (FLIGHT_ID);
ALTER TABLE AIR_FLIGHTS ADD CONSTRAINT FK_FLIGHTNO FOREIGN KEY (FLIGHTNO) REFERENCES AIR_FLIGHTS_SCHEDULES(FLIGHTNO);
CREATE INDEX IDX_FLIGHTNO_FK ON AIR_FLIGHTS(FLIGHTNO);
ALTER TABLE AIR_FLIGHTS ADD CONSTRAINT FK_FROM_AP FOREIGN KEY (FROM_AIRPORT_ID) REFERENCES AIR_AIRPORTS(AIRPORT_ID);
CREATE INDEX IDX_FROM_AP_FK ON AIR_FLIGHTS(FROM_AIRPORT_ID);
ALTER TABLE AIR_FLIGHTS ADD CONSTRAINT FK_TO_AP FOREIGN KEY (TO_AIRPORT_ID) REFERENCES AIR_AIRPORTS(AIRPORT_ID);
CREATE INDEX IDX_TO_AP_FK ON AIR_FLIGHTS(TO_AIRPORT_ID);
ALTER TABLE AIR_FLIGHTS ADD CONSTRAINT FK_AIRPLANE_ID FOREIGN KEY (AIRPLANE_ID) REFERENCES AIR_AIRPLANES(AIRPLANE_ID);
CREATE INDEX IDX_AP_ID_FK ON AIR_FLIGHTS(AIRPLANE_ID);

-- AIR_BOOKINGS
ALTER TABLE AIR_BOOKINGS ADD CONSTRAINT PK_BOOKING PRIMARY KEY (BOOKING_ID);
ALTER TABLE AIR_BOOKINGS ADD CONSTRAINT FK_PASSENGER_ID_BOOKING FOREIGN KEY (PASSENGER_ID) REFERENCES AIR_PASSENGERS(PASSENGER_ID);
CREATE INDEX IDX_PAS_BOOK_FK ON AIR_BOOKINGS(PASSENGER_ID);
ALTER TABLE AIR_BOOKINGS ADD CONSTRAINT FK_FLIGHT_ID_BOOKING FOREIGN KEY (FLIGHT_ID) REFERENCES AIR_FLIGHTS (FLIGHT_ID);
CREATE INDEX IDX_FLGHT_BOOK_FK ON AIR_BOOKINGS(FLIGHT_ID);

-- AIR_PASSENGERS_DETAILS
ALTER TABLE AIR_PASSENGERS_DETAILS ADD CONSTRAINT FK_PASSENGER_ID_DTLS FOREIGN KEY (PASSENGER_ID) REFERENCES AIR_PASSENGERS(PASSENGER_ID);
CREATE INDEX IDX_PSNG_ID_DTLS_FK ON AIR_PASSENGERS_DETAILS(PASSENGER_ID);