DROP TABLE AIR_AIRPORTS_GEO CASCADE CONSTRAINTS;
DROP TABLE AIR_BOOKINGS CASCADE CONSTRAINTS;
DROP TABLE AIR_FLIGHTS CASCADE CONSTRAINTS;
DROP TABLE AIR_FLIGHTS_SCHEDULES CASCADE CONSTRAINTS;
DROP TABLE AIR_PASSENGERS_DETAILS CASCADE CONSTRAINTS;
DROP TABLE AIR_PASSENGERS CASCADE CONSTRAINTS;
DROP TABLE AIR_AIRPLANES CASCADE CONSTRAINTS;
DROP TABLE AIR_AIRPLANE_TYPES CASCADE CONSTRAINTS;
DROP TABLE AIR_AIRPORTS CASCADE CONSTRAINTS;
DROP TABLE AIR_AIRLINES CASCADE CONSTRAINTS;

